from enum import Enum


class AreaTypeV1(str, Enum):

    MUNICIPALITY = "MUNICIPALITY"
    PROVINCE = "PROVINCE"
    REGIONAL_STATE_ADMINISTRATIVE_AGENCY = "REGIONAL_STATE_ADMINISTRATIVE_AGENCY"
    WEATHER_REGION = "WEATHER_REGION"
    COUNTRY = "COUNTRY"
    CITY_REGION = "CITY_REGION"
    TRAVEL_REGION = "TRAVEL_REGION"
    UNKNOWN = "UNKNOWN"
