from enum import Enum


class SituationTypeV1(str, Enum):

    TRAFFIC_ANNOUNCEMENT = "TRAFFIC_ANNOUNCEMENT"
    EXEMPTED_TRANSPORT = "EXEMPTED_TRANSPORT"
    WEIGHT_RESTRICTION = "WEIGHT_RESTRICTION"
    ROAD_WORK = "ROAD_WORK"
