# coding: utf-8

"""
    Digitraffic Road API

    [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.

    The version of the OpenAPI document: Branch: master, tag: 2024.10.28-1 #ef5bdf3 @ 2024-10-29T08:05:03+0000
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.tmsv1_api import TMSV1Api


class TestTMSV1Api(unittest.TestCase):
    """TMSV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = TMSV1Api()

    def tearDown(self) -> None:
        pass

    def test_tms_data(self) -> None:
        """Test case for tms_data

        Current data of TMS stations (Traffic Measurement System / LAM)
        """
        pass

    def test_tms_data_by_id(self) -> None:
        """Test case for tms_data_by_id

        Current data of one TMS station (Traffic Measurement System / LAM)
        """
        pass

    def test_tms_sensor_constants(self) -> None:
        """Test case for tms_sensor_constants

        Current sensor constants and values of TMS stations (Traffic Measurement System / LAM)
        """
        pass

    def test_tms_sensor_constants_by_station_id(self) -> None:
        """Test case for tms_sensor_constants_by_station_id

        Current sensor constants and values of one TMS station (Traffic Measurement System / LAM)
        """
        pass

    def test_tms_sensors(self) -> None:
        """Test case for tms_sensors

        The static information of available sensors of TMS stations (Traffic Measurement System / LAM)
        """
        pass

    def test_tms_station_by_road_station_id(self) -> None:
        """Test case for tms_station_by_road_station_id

        The static information of one TMS station (Traffic Measurement System / LAM)
        """
        pass

    def test_tms_stations(self) -> None:
        """Test case for tms_stations

        The static information of TMS stations (Traffic Measurement System / LAM)
        """
        pass


if __name__ == '__main__':
    unittest.main()
