# coding: utf-8

"""
    Digitraffic Road API

    [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.

    The version of the OpenAPI document: Branch: master, tag: 2024.10.28-1 #ef5bdf3 @ 2024-10-29T08:05:03+0000
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.last_active_itinerary_segment_v1 import LastActiveItinerarySegmentV1

class TestLastActiveItinerarySegmentV1(unittest.TestCase):
    """LastActiveItinerarySegmentV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LastActiveItinerarySegmentV1:
        """Test LastActiveItinerarySegmentV1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LastActiveItinerarySegmentV1`
        """
        model = LastActiveItinerarySegmentV1()
        if include_optional:
            return LastActiveItinerarySegmentV1(
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                legs = [
                    openapi_client.models.itinerary_leg_v1.ItineraryLegV1(
                        road_leg = openapi_client.models.itinerary_road_leg_v1.ItineraryRoadLegV1(
                            road_number = 56, 
                            road_name = '', 
                            start_area = '', 
                            end_area = '', ), 
                        street_name = '', )
                    ]
            )
        else:
            return LastActiveItinerarySegmentV1(
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                legs = [
                    openapi_client.models.itinerary_leg_v1.ItineraryLegV1(
                        road_leg = openapi_client.models.itinerary_road_leg_v1.ItineraryRoadLegV1(
                            road_number = 56, 
                            road_name = '', 
                            start_area = '', 
                            end_area = '', ), 
                        street_name = '', )
                    ],
        )
        """

    def testLastActiveItinerarySegmentV1(self):
        """Test LastActiveItinerarySegmentV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
