# coding: utf-8

"""
    Digitraffic Road API

    [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.

    The version of the OpenAPI document: Branch: master, tag: 2024.10.28-1 #ef5bdf3 @ 2024-10-29T08:05:03+0000
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tms_station_feature_simple_v1 import TmsStationFeatureSimpleV1

class TestTmsStationFeatureSimpleV1(unittest.TestCase):
    """TmsStationFeatureSimpleV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TmsStationFeatureSimpleV1:
        """Test TmsStationFeatureSimpleV1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TmsStationFeatureSimpleV1`
        """
        model = TmsStationFeatureSimpleV1()
        if include_optional:
            return TmsStationFeatureSimpleV1(
                type = '',
                id = 56,
                geometry = openapi_client.models.point.Point(),
                properties = openapi_client.models.tms_station_properties_simple_v1.TmsStationPropertiesSimpleV1(
                    id = 56, 
                    tms_number = 56, 
                    name = '', 
                    collection_status = 'GATHERING', 
                    state = 'OK', 
                    data_updated_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return TmsStationFeatureSimpleV1(
                type = '',
                id = 56,
                geometry = openapi_client.models.point.Point(),
                properties = openapi_client.models.tms_station_properties_simple_v1.TmsStationPropertiesSimpleV1(
                    id = 56, 
                    tms_number = 56, 
                    name = '', 
                    collection_status = 'GATHERING', 
                    state = 'OK', 
                    data_updated_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testTmsStationFeatureSimpleV1(self):
        """Test TmsStationFeatureSimpleV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
