# coding: utf-8

"""
    Digitraffic Road API

    [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.

    The version of the OpenAPI document: Branch: master, tag: 2024.10.28-1 #ef5bdf3 @ 2024-10-29T08:05:03+0000
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.weathercam_v1_api import WeathercamV1Api


class TestWeathercamV1Api(unittest.TestCase):
    """WeathercamV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = WeathercamV1Api()

    def tearDown(self) -> None:
        pass

    def test_get_weathercam_presets_history_by_id(self) -> None:
        """Test case for get_weathercam_presets_history_by_id

        Weathercam presets history for given camera
        """
        pass

    def test_get_weathercams_presets_history(self) -> None:
        """Test case for get_weathercams_presets_history

        Weathercams presets history for all cameras
        """
        pass

    def test_weathercam_datas_by_station_id(self) -> None:
        """Test case for weathercam_datas_by_station_id

        Current data of weathercam
        """
        pass

    def test_weathercam_preset_publicity_changes_after(self) -> None:
        """Test case for weathercam_preset_publicity_changes_after

        Weathercam presets publicity changes after given time. Result is in ascending order by presetId and lastModified -fields. 
        """
        pass

    def test_weathercam_station(self) -> None:
        """Test case for weathercam_station

        The static information of weather camera station
        """
        pass

    def test_weathercam_stations(self) -> None:
        """Test case for weathercam_stations

        The static information of weather camera stations
        """
        pass

    def test_weathercams_datas(self) -> None:
        """Test case for weathercams_datas

        Current data of weathercams
        """
        pass


if __name__ == '__main__':
    unittest.main()
