# coding: utf-8

"""
    Digitraffic Road API

    [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.

    The version of the OpenAPI document: Branch: master, tag: 2024.10.28-1 #ef5bdf3 @ 2024-10-29T08:05:03+0000
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.forecast_section_weather_forecast_dto_v1 import ForecastSectionWeatherForecastDtoV1

class TestForecastSectionWeatherForecastDtoV1(unittest.TestCase):
    """ForecastSectionWeatherForecastDtoV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForecastSectionWeatherForecastDtoV1:
        """Test ForecastSectionWeatherForecastDtoV1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForecastSectionWeatherForecastDtoV1`
        """
        model = ForecastSectionWeatherForecastDtoV1()
        if include_optional:
            return ForecastSectionWeatherForecastDtoV1(
                time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                type = 'OBSERVATION',
                forecast_name = '',
                daylight = True,
                road_temperature = 1.337,
                temperature = 1.337,
                wind_speed = 1.337,
                wind_direction = 56,
                overall_road_condition = 'NORMAL_CONDITION',
                weather_symbol = '',
                reliability = 'SUCCESSFUL',
                forecast_condition_reason = openapi_client.models.forecast_condition_reason_dto_v1.ForecastConditionReasonDtoV1(
                    precipitation_condition = 'NO_DATA_AVAILABLE', 
                    road_condition = 'DRY', 
                    wind_condition = 'WEAK', 
                    freezing_rain_condition = True, 
                    winter_slipperiness = True, 
                    visibility_condition = 'FAIRLY_POOR', 
                    friction_condition = 'SLIPPERY', ),
                data_updated_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ForecastSectionWeatherForecastDtoV1(
                data_updated_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testForecastSectionWeatherForecastDtoV1(self):
        """Test ForecastSectionWeatherForecastDtoV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
