# coding: utf-8

"""
    Digitraffic Road API

    [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.

    The version of the OpenAPI document: Branch: master, tag: 2024.10.28-1 #ef5bdf3 @ 2024-10-29T08:05:03+0000
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.beta_api import BetaApi


class TestBetaApi(unittest.TestCase):
    """BetaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BetaApi()

    def tearDown(self) -> None:
        pass

    def test_tms_data_datex2_json(self) -> None:
        """Test case for tms_data_datex2_json

        Current data of TMS Stations in Datex2 format (Traffic Measurement System / LAM)
        """
        pass

    def test_tms_data_datex2_xml(self) -> None:
        """Test case for tms_data_datex2_xml

        Current data of TMS Stations in Datex2 format (Traffic Measurement System / LAM)
        """
        pass

    def test_tms_stations_datex2_json(self) -> None:
        """Test case for tms_stations_datex2_json

        The static information of TMS stations in Datex2 format (Traffic Measurement System / LAM)
        """
        pass

    def test_tms_stations_datex2_xml(self) -> None:
        """Test case for tms_stations_datex2_xml

        The static information of TMS stations in Datex2 format (Traffic Measurement System / LAM)
        """
        pass

    def test_weather_data_history(self) -> None:
        """Test case for weather_data_history

        List the history of sensor values from the weather road station
        """
        pass

    def test_weather_data_history1(self) -> None:
        """Test case for weather_data_history1

        List the history of sensor value from the weather road station
        """
        pass


if __name__ == '__main__':
    unittest.main()
