# coding: utf-8

"""
    Digitraffic Road API

    [OpenAPI document](/swagger/openapi.json)   Digitraffic is a service operated by the [Fintraffic](https://www.fintraffic.fi) offering real time traffic information. Currently the service covers *road, marine and rail* traffic. More information can be found at the [Digitraffic website](https://www.digitraffic.fi/)   The service has a public Google-group [road.digitraffic.fi](https://groups.google.com/forum/#!forum/roaddigitrafficfi) for communication between developers, service administrators and Fintraffic. The discussion in the forum is mostly in Finnish, but you're welcome to communicate in English too.   ### General notes of the API * Many Digitraffic APIs use GeoJSON as data format. Definition of the GeoJSON format can be found at https://tools.ietf.org/html/rfc7946. * For dates and times [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format is used with \"Zulu\" zero offset from UTC unless otherwise specified (i.e., \"yyyy-mm-ddThh:mm:ss[.mmm]Z\"). E.g. 2019-11-01T06:30:00Z.

    The version of the OpenAPI document: Branch: master, tag: 2024.10.28-1 #ef5bdf3 @ 2024-10-29T08:05:03+0000
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.site_measurements import SiteMeasurements

class TestSiteMeasurements(unittest.TestCase):
    """SiteMeasurements unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SiteMeasurements:
        """Test SiteMeasurements
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SiteMeasurements`
        """
        model = SiteMeasurements()
        if include_optional:
            return SiteMeasurements(
                measurement_site_reference = openapi_client.models._measurement_site_versioned_reference._MeasurementSiteVersionedReference(
                    id = '', 
                    version = '', ),
                physical_quantities = [
                    openapi_client.models._site_measurements_index_physical_quantity._SiteMeasurementsIndexPhysicalQuantity(
                        physical_quantity = openapi_client.models.physical_quantity.PhysicalQuantity(
                            forecast = True, 
                            measurement_equipment_type_used = openapi_client.models.multilingual_string.MultilingualString(
                                values = openapi_client.models.values.Values(
                                    values = [
                                        openapi_client.models.multilingual_string_value.MultilingualStringValue(
                                            value = '', 
                                            lang = '', )
                                        ], ), ), 
                            pertinent_location = openapi_client.models.location_reference.LocationReference(
                                get_location_reference_extension = openapi_client.models._location_reference_extension_type._LocationReferenceExtensionType(
                                    facility_location = openapi_client.models.facility_location.FacilityLocation(
                                        time_zone = '', 
                                        address = openapi_client.models.address.Address(
                                            postcode = '', 
                                            city = openapi_client.models.multilingual_string.MultilingualString(
                                                values = openapi_client.models.values.Values(
                                                    values = [
                                                        openapi_client.models.multilingual_string_value.MultilingualStringValue(
                                                            value = '', 
                                                            lang = '', )
                                                        ], ), ), 
                                            country_code = '', 
                                            address_lines = [
                                                openapi_client.models.address_line.AddressLine(
                                                    type = openapi_client.models._address_line_type_enum._AddressLineTypeEnum(
                                                        value = 'APARTMENT', 
                                                        get_extended_value = '', ), 
                                                    text = , 
                                                    get_address_line_extension = openapi_client.models._extension_type._ExtensionType(
                                                        anies = [
                                                            openapi_client.models.element.Element(
                                                                schema_type_info = openapi_client.models.type_info.TypeInfo(
                                                                    type_name = '', 
                                                                    type_namespace = '', ), 
                                                                attribute_node_ns = openapi_client.models.attr.Attr(
                                                                    name = '', 
                                                                    value = '', 
                                                                    specified = True, 
                                                                    owner_element = openapi_client.models.element.Element(
                                                                        attribute_node = openapi_client.models.attr.Attr(
                                                                            name = '', 
                                                                            value = '', 
                                                                            specified = True, 
                                                                            id = True, 
                                                                            attributes = openapi_client.models.named_node_map.NamedNodeMap(
                                                                                length = 56, 
                                                                                named_item = openapi_client.models.node.Node(
                                                                                    local_name = '', 
                                                                                    node_name = '', 
                                                                                    node_value = '', 
                                                                                    parent_node = openapi_client.models.node.Node(
                                                                                        local_name = '', 
                                                                                        node_name = '', 
                                                                                        node_value = '', 
                                                                                        child_nodes = openapi_client.models.node_list.NodeList(
                                                                                            length = 56, ), 
                                                                                        first_child = , 
                                                                                        last_child = , 
                                                                                        previous_sibling = , 
                                                                                        next_sibling = , 
                                                                                        owner_document = openapi_client.models.document.Document(
                                                                                            doctype = openapi_client.models.document_type.DocumentType(
                                                                                                name = '', 
                                                                                                public_id = '', 
                                                                                                system_id = '', 
                                                                                                entities = openapi_client.models.named_node_map.NamedNodeMap(
                                                                                                    length = 56, 
                                                                                                    named_item_ns = , ), 
                                                                                                notations = , 
                                                                                                internal_subset = '', 
                                                                                                local_name = '', 
                                                                                                node_name = '', 
                                                                                                node_value = '', 
                                                                                                namespace_uri = '', 
                                                                                                base_uri = '', 
                                                                                                text_content = '', 
                                                                                                prefix = '', 
                                                                                                node_type = 56, ), 
                                                                                            document_element = , 
                                                                                            input_encoding = '', 
                                                                                            xml_encoding = '', 
                                                                                            xml_standalone = True, 
                                                                                            xml_version = '', 
                                                                                            strict_error_checking = True, 
                                                                                            document_uri = '', 
                                                                                            dom_config = openapi_client.models.dom_configuration.DOMConfiguration(
                                                                                                parameter_names = openapi_client.models.dom_string_list.DOMStringList(
                                                                                                    length = 56, ), ), 
                                                                                            implementation = openapi_client.models.dom_implementation.DOMImplementation(), 
                                                                                            local_name = '', 
                                                                                            node_name = '', 
                                                                                            node_value = '', 
                                                                                            namespace_uri = '', 
                                                                                            base_uri = '', 
                                                                                            text_content = '', 
                                                                                            prefix = '', 
                                                                                            node_type = 56, ), 
                                                                                        namespace_uri = '', 
                                                                                        base_uri = '', 
                                                                                        text_content = '', 
                                                                                        prefix = '', 
                                                                                        node_type = 56, ), 
                                                                                    child_nodes = openapi_client.models.node_list.NodeList(
                                                                                        length = 56, ), 
                                                                                    first_child = , 
                                                                                    last_child = , 
                                                                                    previous_sibling = , 
                                                                                    next_sibling = , 
                                                                                    owner_document = openapi_client.models.document.Document(
                                                                                        input_encoding = '', 
                                                                                        xml_encoding = '', 
                                                                                        xml_standalone = True, 
                                                                                        xml_version = '', 
                                                                                        strict_error_checking = True, 
                                                                                        document_uri = '', 
                                                                                        implementation = openapi_client.models.dom_implementation.DOMImplementation(), 
                                                                                        local_name = '', 
                                                                                        node_name = '', 
                                                                                        node_value = '', 
                                                                                        namespace_uri = '', 
                                                                                        base_uri = '', 
                                                                                        text_content = '', 
                                                                                        prefix = '', 
                                                                                        node_type = 56, ), 
                                                                                    namespace_uri = '', 
                                                                                    base_uri = '', 
                                                                                    text_content = '', 
                                                                                    prefix = '', 
                                                                                    node_type = 56, ), 
                                                                                named_item_ns = , ), 
                                                                            local_name = '', 
                                                                            node_name = '', 
                                                                            node_value = '', 
                                                                            parent_node = , 
                                                                            child_nodes = , 
                                                                            first_child = , 
                                                                            last_child = , 
                                                                            previous_sibling = , 
                                                                            next_sibling = , 
                                                                            owner_document = , 
                                                                            namespace_uri = '', 
                                                                            base_uri = '', 
                                                                            text_content = '', 
                                                                            prefix = '', 
                                                                            node_type = 56, ), 
                                                                        tag_name = '', 
                                                                        attributes = , 
                                                                        local_name = '', 
                                                                        node_name = '', 
                                                                        node_value = '', 
                                                                        parent_node = , 
                                                                        child_nodes = , 
                                                                        first_child = , 
                                                                        last_child = , 
                                                                        previous_sibling = , 
                                                                        next_sibling = , 
                                                                        owner_document = , 
                                                                        namespace_uri = '', 
                                                                        base_uri = '', 
                                                                        text_content = '', 
                                                                        prefix = '', 
                                                                        node_type = 56, ), 
                                                                    id = True, 
                                                                    attributes = , 
                                                                    local_name = '', 
                                                                    node_name = '', 
                                                                    node_value = '', 
                                                                    parent_node = , 
                                                                    child_nodes = , 
                                                                    first_child = , 
                                                                    last_child = , 
                                                                    previous_sibling = , 
                                                                    next_sibling = , 
                                                                    owner_document = , 
                                                                    namespace_uri = '', 
                                                                    base_uri = '', 
                                                                    text_content = '', 
                                                                    prefix = '', 
                                                                    node_type = 56, ), 
                                                                attribute_node = , 
                                                                tag_name = '', 
                                                                attributes = , 
                                                                local_name = '', 
                                                                node_name = '', 
                                                                node_value = '', 
                                                                parent_node = , 
                                                                child_nodes = , 
                                                                first_child = , 
                                                                last_child = , 
                                                                previous_sibling = , 
                                                                next_sibling = , 
                                                                owner_document = , 
                                                                namespace_uri = '', 
                                                                base_uri = '', 
                                                                text_content = '', 
                                                                prefix = '', 
                                                                node_type = 56, )
                                                            ], ), 
                                                    order = 56, )
                                                ], 
                                            get_address_extension = openapi_client.models._extension_type._ExtensionType(), ), ), 
                                    anies = [
                                        
                                        ], ), ), 
                            physical_quantity_faults = [
                                openapi_client.models.physical_quantity_fault.PhysicalQuantityFault(
                                    fault_last_update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    get_fault_extension = , 
                                    physical_quantity_fault_type = openapi_client.models._physical_quantity_fault_enum._PhysicalQuantityFaultEnum(
                                        value = 'INTERMITTENT_DATA_VALUES', 
                                        get_extended_value = '', ), 
                                    get_physical_quantity_fault_extension = , )
                                ], 
                            source = openapi_client.models.source.Source(
                                source_country = '', 
                                source_identification = '', 
                                source_name = , 
                                source_type = openapi_client.models._source_type_enum._SourceTypeEnum(
                                    value = 'AUTOMOBILE_CLUB_PATROL', 
                                    get_extended_value = '', ), 
                                reliable = True, 
                                get_source_extension = , ), 
                            information_manager_override = openapi_client.models.international_identifier.InternationalIdentifier(
                                country = 'AT', 
                                national_identifier = '', 
                                get_international_identifier_extension = , 
                                international_identifier_extension = , ), 
                            get_physical_quantity_extension = , ), 
                        index = 56, )
                    ],
                measurement_time_default = openapi_client.models.measurement_or_calculation_time.MeasurementOrCalculationTime(
                    time_meaning = openapi_client.models._time_meaning_enum._TimeMeaningEnum(
                        value = 'BEGIN_TIME', 
                        get_extended_value = '', ), 
                    time_value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    period = openapi_client.models.period.Period(
                        start_of_period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_of_period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        period_name = openapi_client.models.multilingual_string.MultilingualString(
                            values = openapi_client.models.values.Values(
                                values = [
                                    openapi_client.models.multilingual_string_value.MultilingualStringValue(
                                        value = '', 
                                        lang = '', )
                                    ], ), ), 
                        recurring_time_period_of_daies = [
                            openapi_client.models.time_period_of_day.TimePeriodOfDay(
                                start_time_of_period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                end_time_of_period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                get_time_period_of_day_extension = openapi_client.models._extension_type._ExtensionType(
                                    anies = [
                                        openapi_client.models.element.Element(
                                            schema_type_info = openapi_client.models.type_info.TypeInfo(
                                                type_name = '', 
                                                type_namespace = '', ), 
                                            attribute_node_ns = openapi_client.models.attr.Attr(
                                                name = '', 
                                                value = '', 
                                                specified = True, 
                                                owner_element = openapi_client.models.element.Element(
                                                    attribute_node = openapi_client.models.attr.Attr(
                                                        name = '', 
                                                        value = '', 
                                                        specified = True, 
                                                        id = True, 
                                                        attributes = openapi_client.models.named_node_map.NamedNodeMap(
                                                            length = 56, 
                                                            named_item = openapi_client.models.node.Node(
                                                                local_name = '', 
                                                                node_name = '', 
                                                                node_value = '', 
                                                                parent_node = openapi_client.models.node.Node(
                                                                    local_name = '', 
                                                                    node_name = '', 
                                                                    node_value = '', 
                                                                    child_nodes = openapi_client.models.node_list.NodeList(
                                                                        length = 56, ), 
                                                                    first_child = , 
                                                                    last_child = , 
                                                                    previous_sibling = , 
                                                                    next_sibling = , 
                                                                    owner_document = openapi_client.models.document.Document(
                                                                        doctype = openapi_client.models.document_type.DocumentType(
                                                                            name = '', 
                                                                            public_id = '', 
                                                                            system_id = '', 
                                                                            entities = openapi_client.models.named_node_map.NamedNodeMap(
                                                                                length = 56, 
                                                                                named_item_ns = , ), 
                                                                            notations = , 
                                                                            internal_subset = '', 
                                                                            local_name = '', 
                                                                            node_name = '', 
                                                                            node_value = '', 
                                                                            namespace_uri = '', 
                                                                            base_uri = '', 
                                                                            text_content = '', 
                                                                            prefix = '', 
                                                                            node_type = 56, ), 
                                                                        document_element = , 
                                                                        input_encoding = '', 
                                                                        xml_encoding = '', 
                                                                        xml_standalone = True, 
                                                                        xml_version = '', 
                                                                        strict_error_checking = True, 
                                                                        document_uri = '', 
                                                                        dom_config = openapi_client.models.dom_configuration.DOMConfiguration(
                                                                            parameter_names = openapi_client.models.dom_string_list.DOMStringList(
                                                                                length = 56, ), ), 
                                                                        implementation = openapi_client.models.dom_implementation.DOMImplementation(), 
                                                                        local_name = '', 
                                                                        node_name = '', 
                                                                        node_value = '', 
                                                                        namespace_uri = '', 
                                                                        base_uri = '', 
                                                                        text_content = '', 
                                                                        prefix = '', 
                                                                        node_type = 56, ), 
                                                                    namespace_uri = '', 
                                                                    base_uri = '', 
                                                                    text_content = '', 
                                                                    prefix = '', 
                                                                    node_type = 56, ), 
                                                                child_nodes = openapi_client.models.node_list.NodeList(
                                                                    length = 56, ), 
                                                                first_child = , 
                                                                last_child = , 
                                                                previous_sibling = , 
                                                                next_sibling = , 
                                                                owner_document = openapi_client.models.document.Document(
                                                                    input_encoding = '', 
                                                                    xml_encoding = '', 
                                                                    xml_standalone = True, 
                                                                    xml_version = '', 
                                                                    strict_error_checking = True, 
                                                                    document_uri = '', 
                                                                    implementation = openapi_client.models.dom_implementation.DOMImplementation(), 
                                                                    local_name = '', 
                                                                    node_name = '', 
                                                                    node_value = '', 
                                                                    namespace_uri = '', 
                                                                    base_uri = '', 
                                                                    text_content = '', 
                                                                    prefix = '', 
                                                                    node_type = 56, ), 
                                                                namespace_uri = '', 
                                                                base_uri = '', 
                                                                text_content = '', 
                                                                prefix = '', 
                                                                node_type = 56, ), 
                                                            named_item_ns = , ), 
                                                        local_name = '', 
                                                        node_name = '', 
                                                        node_value = '', 
                                                        parent_node = , 
                                                        child_nodes = , 
                                                        first_child = , 
                                                        last_child = , 
                                                        previous_sibling = , 
                                                        next_sibling = , 
                                                        owner_document = , 
                                                        namespace_uri = '', 
                                                        base_uri = '', 
                                                        text_content = '', 
                                                        prefix = '', 
                                                        node_type = 56, ), 
                                                    tag_name = '', 
                                                    attributes = , 
                                                    local_name = '', 
                                                    node_name = '', 
                                                    node_value = '', 
                                                    parent_node = , 
                                                    child_nodes = , 
                                                    first_child = , 
                                                    last_child = , 
                                                    previous_sibling = , 
                                                    next_sibling = , 
                                                    owner_document = , 
                                                    namespace_uri = '', 
                                                    base_uri = '', 
                                                    text_content = '', 
                                                    prefix = '', 
                                                    node_type = 56, ), 
                                                id = True, 
                                                attributes = , 
                                                local_name = '', 
                                                node_name = '', 
                                                node_value = '', 
                                                parent_node = , 
                                                child_nodes = , 
                                                first_child = , 
                                                last_child = , 
                                                previous_sibling = , 
                                                next_sibling = , 
                                                owner_document = , 
                                                namespace_uri = '', 
                                                base_uri = '', 
                                                text_content = '', 
                                                prefix = '', 
                                                node_type = 56, ), 
                                            attribute_node = , 
                                            tag_name = '', 
                                            attributes = , 
                                            local_name = '', 
                                            node_name = '', 
                                            node_value = '', 
                                            parent_node = , 
                                            child_nodes = , 
                                            first_child = , 
                                            last_child = , 
                                            previous_sibling = , 
                                            next_sibling = , 
                                            owner_document = , 
                                            namespace_uri = '', 
                                            base_uri = '', 
                                            text_content = '', 
                                            prefix = '', 
                                            node_type = 56, )
                                        ], ), )
                            ], 
                        recurring_day_week_month_periods = [
                            openapi_client.models.day_week_month.DayWeekMonth(
                                applicable_daies = [
                                    openapi_client.models._day_enum._DayEnum(
                                        value = 'MONDAY', 
                                        get_extended_value = '', )
                                    ], 
                                applicable_months = [
                                    openapi_client.models._month_of_year_enum._MonthOfYearEnum(
                                        value = 'JANUARY', 
                                        get_extended_value = '', )
                                    ], 
                                get_day_week_month_extension = openapi_client.models._extension_type._ExtensionType(), )
                            ], 
                        recurring_special_daies = [
                            openapi_client.models.special_day.SpecialDay(
                                intersect_with_applicable_days = True, 
                                special_day_type = openapi_client.models._special_day_type_enum._SpecialDayTypeEnum(
                                    value = 'DAY_BEFORE_PUBLIC_HOLIDAY', 
                                    get_extended_value = '', ), 
                                public_event = openapi_client.models._public_event_type_enum._PublicEventTypeEnum(
                                    value = 'AGRICULTURAL_SHOW', 
                                    get_extended_value = '', ), 
                                named_areas = [
                                    openapi_client.models.named_area.NamedArea(
                                        area_name = openapi_client.models.multilingual_string.MultilingualString(
                                            values = openapi_client.models.values.Values(
                                                values = [
                                                    openapi_client.models.multilingual_string_value.MultilingualStringValue(
                                                        value = '', 
                                                        lang = '', )
                                                    ], ), ), 
                                        named_area_type = openapi_client.models.named_area_type_enum_g.NamedAreaTypeEnumG(
                                            value = 'applicationRegion', 
                                            extended_value_g = '', ), 
                                        country = '', 
                                        named_area_extension_g = openapi_client.models.named_area_extension_g.namedAreaExtensionG(), )
                                    ], 
                                get_special_day_extension = , )
                            ], 
                        get_period_extension = , ), 
                    get_measurement_or_calculation_time_extension = , 
                    time_precision = 'TENTHS_OF_SECOND', ),
                get_site_measurements_extension = openapi_client.models._extension_type._ExtensionType(
                    anies = [
                        openapi_client.models.element.Element(
                            schema_type_info = openapi_client.models.type_info.TypeInfo(
                                type_name = '', 
                                type_namespace = '', ), 
                            attribute_node_ns = openapi_client.models.attr.Attr(
                                name = '', 
                                value = '', 
                                specified = True, 
                                owner_element = openapi_client.models.element.Element(
                                    attribute_node = openapi_client.models.attr.Attr(
                                        name = '', 
                                        value = '', 
                                        specified = True, 
                                        id = True, 
                                        attributes = openapi_client.models.named_node_map.NamedNodeMap(
                                            length = 56, 
                                            named_item = openapi_client.models.node.Node(
                                                local_name = '', 
                                                node_name = '', 
                                                node_value = '', 
                                                parent_node = openapi_client.models.node.Node(
                                                    local_name = '', 
                                                    node_name = '', 
                                                    node_value = '', 
                                                    child_nodes = openapi_client.models.node_list.NodeList(
                                                        length = 56, ), 
                                                    first_child = , 
                                                    last_child = , 
                                                    previous_sibling = , 
                                                    next_sibling = , 
                                                    owner_document = openapi_client.models.document.Document(
                                                        doctype = openapi_client.models.document_type.DocumentType(
                                                            name = '', 
                                                            public_id = '', 
                                                            system_id = '', 
                                                            entities = openapi_client.models.named_node_map.NamedNodeMap(
                                                                length = 56, 
                                                                named_item_ns = , ), 
                                                            notations = , 
                                                            internal_subset = '', 
                                                            local_name = '', 
                                                            node_name = '', 
                                                            node_value = '', 
                                                            namespace_uri = '', 
                                                            base_uri = '', 
                                                            text_content = '', 
                                                            prefix = '', 
                                                            node_type = 56, ), 
                                                        document_element = , 
                                                        input_encoding = '', 
                                                        xml_encoding = '', 
                                                        xml_standalone = True, 
                                                        xml_version = '', 
                                                        strict_error_checking = True, 
                                                        document_uri = '', 
                                                        dom_config = openapi_client.models.dom_configuration.DOMConfiguration(
                                                            parameter_names = openapi_client.models.dom_string_list.DOMStringList(
                                                                length = 56, ), ), 
                                                        implementation = openapi_client.models.dom_implementation.DOMImplementation(), 
                                                        local_name = '', 
                                                        node_name = '', 
                                                        node_value = '', 
                                                        namespace_uri = '', 
                                                        base_uri = '', 
                                                        text_content = '', 
                                                        prefix = '', 
                                                        node_type = 56, ), 
                                                    namespace_uri = '', 
                                                    base_uri = '', 
                                                    text_content = '', 
                                                    prefix = '', 
                                                    node_type = 56, ), 
                                                child_nodes = openapi_client.models.node_list.NodeList(
                                                    length = 56, ), 
                                                first_child = , 
                                                last_child = , 
                                                previous_sibling = , 
                                                next_sibling = , 
                                                owner_document = openapi_client.models.document.Document(
                                                    input_encoding = '', 
                                                    xml_encoding = '', 
                                                    xml_standalone = True, 
                                                    xml_version = '', 
                                                    strict_error_checking = True, 
                                                    document_uri = '', 
                                                    implementation = openapi_client.models.dom_implementation.DOMImplementation(), 
                                                    local_name = '', 
                                                    node_name = '', 
                                                    node_value = '', 
                                                    namespace_uri = '', 
                                                    base_uri = '', 
                                                    text_content = '', 
                                                    prefix = '', 
                                                    node_type = 56, ), 
                                                namespace_uri = '', 
                                                base_uri = '', 
                                                text_content = '', 
                                                prefix = '', 
                                                node_type = 56, ), 
                                            named_item_ns = , ), 
                                        local_name = '', 
                                        node_name = '', 
                                        node_value = '', 
                                        parent_node = , 
                                        child_nodes = , 
                                        first_child = , 
                                        last_child = , 
                                        previous_sibling = , 
                                        next_sibling = , 
                                        owner_document = , 
                                        namespace_uri = '', 
                                        base_uri = '', 
                                        text_content = '', 
                                        prefix = '', 
                                        node_type = 56, ), 
                                    tag_name = '', 
                                    attributes = , 
                                    local_name = '', 
                                    node_name = '', 
                                    node_value = '', 
                                    parent_node = , 
                                    child_nodes = , 
                                    first_child = , 
                                    last_child = , 
                                    previous_sibling = , 
                                    next_sibling = , 
                                    owner_document = , 
                                    namespace_uri = '', 
                                    base_uri = '', 
                                    text_content = '', 
                                    prefix = '', 
                                    node_type = 56, ), 
                                id = True, 
                                attributes = , 
                                local_name = '', 
                                node_name = '', 
                                node_value = '', 
                                parent_node = , 
                                child_nodes = , 
                                first_child = , 
                                last_child = , 
                                previous_sibling = , 
                                next_sibling = , 
                                owner_document = , 
                                namespace_uri = '', 
                                base_uri = '', 
                                text_content = '', 
                                prefix = '', 
                                node_type = 56, ), 
                            attribute_node = , 
                            tag_name = '', 
                            attributes = , 
                            local_name = '', 
                            node_name = '', 
                            node_value = '', 
                            parent_node = , 
                            child_nodes = , 
                            first_child = , 
                            last_child = , 
                            previous_sibling = , 
                            next_sibling = , 
                            owner_document = , 
                            namespace_uri = '', 
                            base_uri = '', 
                            text_content = '', 
                            prefix = '', 
                            node_type = 56, )
                        ], )
            )
        else:
            return SiteMeasurements(
                measurement_site_reference = openapi_client.models._measurement_site_versioned_reference._MeasurementSiteVersionedReference(
                    id = '', 
                    version = '', ),
                measurement_time_default = openapi_client.models.measurement_or_calculation_time.MeasurementOrCalculationTime(
                    time_meaning = openapi_client.models._time_meaning_enum._TimeMeaningEnum(
                        value = 'BEGIN_TIME', 
                        get_extended_value = '', ), 
                    time_value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    period = openapi_client.models.period.Period(
                        start_of_period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_of_period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        period_name = openapi_client.models.multilingual_string.MultilingualString(
                            values = openapi_client.models.values.Values(
                                values = [
                                    openapi_client.models.multilingual_string_value.MultilingualStringValue(
                                        value = '', 
                                        lang = '', )
                                    ], ), ), 
                        recurring_time_period_of_daies = [
                            openapi_client.models.time_period_of_day.TimePeriodOfDay(
                                start_time_of_period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                end_time_of_period = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                get_time_period_of_day_extension = openapi_client.models._extension_type._ExtensionType(
                                    anies = [
                                        openapi_client.models.element.Element(
                                            schema_type_info = openapi_client.models.type_info.TypeInfo(
                                                type_name = '', 
                                                type_namespace = '', ), 
                                            attribute_node_ns = openapi_client.models.attr.Attr(
                                                name = '', 
                                                value = '', 
                                                specified = True, 
                                                owner_element = openapi_client.models.element.Element(
                                                    attribute_node = openapi_client.models.attr.Attr(
                                                        name = '', 
                                                        value = '', 
                                                        specified = True, 
                                                        id = True, 
                                                        attributes = openapi_client.models.named_node_map.NamedNodeMap(
                                                            length = 56, 
                                                            named_item = openapi_client.models.node.Node(
                                                                local_name = '', 
                                                                node_name = '', 
                                                                node_value = '', 
                                                                parent_node = openapi_client.models.node.Node(
                                                                    local_name = '', 
                                                                    node_name = '', 
                                                                    node_value = '', 
                                                                    child_nodes = openapi_client.models.node_list.NodeList(
                                                                        length = 56, ), 
                                                                    first_child = , 
                                                                    last_child = , 
                                                                    previous_sibling = , 
                                                                    next_sibling = , 
                                                                    owner_document = openapi_client.models.document.Document(
                                                                        doctype = openapi_client.models.document_type.DocumentType(
                                                                            name = '', 
                                                                            public_id = '', 
                                                                            system_id = '', 
                                                                            entities = openapi_client.models.named_node_map.NamedNodeMap(
                                                                                length = 56, 
                                                                                named_item_ns = , ), 
                                                                            notations = , 
                                                                            internal_subset = '', 
                                                                            local_name = '', 
                                                                            node_name = '', 
                                                                            node_value = '', 
                                                                            namespace_uri = '', 
                                                                            base_uri = '', 
                                                                            text_content = '', 
                                                                            prefix = '', 
                                                                            node_type = 56, ), 
                                                                        document_element = , 
                                                                        input_encoding = '', 
                                                                        xml_encoding = '', 
                                                                        xml_standalone = True, 
                                                                        xml_version = '', 
                                                                        strict_error_checking = True, 
                                                                        document_uri = '', 
                                                                        dom_config = openapi_client.models.dom_configuration.DOMConfiguration(
                                                                            parameter_names = openapi_client.models.dom_string_list.DOMStringList(
                                                                                length = 56, ), ), 
                                                                        implementation = openapi_client.models.dom_implementation.DOMImplementation(), 
                                                                        local_name = '', 
                                                                        node_name = '', 
                                                                        node_value = '', 
                                                                        namespace_uri = '', 
                                                                        base_uri = '', 
                                                                        text_content = '', 
                                                                        prefix = '', 
                                                                        node_type = 56, ), 
                                                                    namespace_uri = '', 
                                                                    base_uri = '', 
                                                                    text_content = '', 
                                                                    prefix = '', 
                                                                    node_type = 56, ), 
                                                                child_nodes = openapi_client.models.node_list.NodeList(
                                                                    length = 56, ), 
                                                                first_child = , 
                                                                last_child = , 
                                                                previous_sibling = , 
                                                                next_sibling = , 
                                                                owner_document = openapi_client.models.document.Document(
                                                                    input_encoding = '', 
                                                                    xml_encoding = '', 
                                                                    xml_standalone = True, 
                                                                    xml_version = '', 
                                                                    strict_error_checking = True, 
                                                                    document_uri = '', 
                                                                    implementation = openapi_client.models.dom_implementation.DOMImplementation(), 
                                                                    local_name = '', 
                                                                    node_name = '', 
                                                                    node_value = '', 
                                                                    namespace_uri = '', 
                                                                    base_uri = '', 
                                                                    text_content = '', 
                                                                    prefix = '', 
                                                                    node_type = 56, ), 
                                                                namespace_uri = '', 
                                                                base_uri = '', 
                                                                text_content = '', 
                                                                prefix = '', 
                                                                node_type = 56, ), 
                                                            named_item_ns = , ), 
                                                        local_name = '', 
                                                        node_name = '', 
                                                        node_value = '', 
                                                        parent_node = , 
                                                        child_nodes = , 
                                                        first_child = , 
                                                        last_child = , 
                                                        previous_sibling = , 
                                                        next_sibling = , 
                                                        owner_document = , 
                                                        namespace_uri = '', 
                                                        base_uri = '', 
                                                        text_content = '', 
                                                        prefix = '', 
                                                        node_type = 56, ), 
                                                    tag_name = '', 
                                                    attributes = , 
                                                    local_name = '', 
                                                    node_name = '', 
                                                    node_value = '', 
                                                    parent_node = , 
                                                    child_nodes = , 
                                                    first_child = , 
                                                    last_child = , 
                                                    previous_sibling = , 
                                                    next_sibling = , 
                                                    owner_document = , 
                                                    namespace_uri = '', 
                                                    base_uri = '', 
                                                    text_content = '', 
                                                    prefix = '', 
                                                    node_type = 56, ), 
                                                id = True, 
                                                attributes = , 
                                                local_name = '', 
                                                node_name = '', 
                                                node_value = '', 
                                                parent_node = , 
                                                child_nodes = , 
                                                first_child = , 
                                                last_child = , 
                                                previous_sibling = , 
                                                next_sibling = , 
                                                owner_document = , 
                                                namespace_uri = '', 
                                                base_uri = '', 
                                                text_content = '', 
                                                prefix = '', 
                                                node_type = 56, ), 
                                            attribute_node = , 
                                            tag_name = '', 
                                            attributes = , 
                                            local_name = '', 
                                            node_name = '', 
                                            node_value = '', 
                                            parent_node = , 
                                            child_nodes = , 
                                            first_child = , 
                                            last_child = , 
                                            previous_sibling = , 
                                            next_sibling = , 
                                            owner_document = , 
                                            namespace_uri = '', 
                                            base_uri = '', 
                                            text_content = '', 
                                            prefix = '', 
                                            node_type = 56, )
                                        ], ), )
                            ], 
                        recurring_day_week_month_periods = [
                            openapi_client.models.day_week_month.DayWeekMonth(
                                applicable_daies = [
                                    openapi_client.models._day_enum._DayEnum(
                                        value = 'MONDAY', 
                                        get_extended_value = '', )
                                    ], 
                                applicable_months = [
                                    openapi_client.models._month_of_year_enum._MonthOfYearEnum(
                                        value = 'JANUARY', 
                                        get_extended_value = '', )
                                    ], 
                                get_day_week_month_extension = openapi_client.models._extension_type._ExtensionType(), )
                            ], 
                        recurring_special_daies = [
                            openapi_client.models.special_day.SpecialDay(
                                intersect_with_applicable_days = True, 
                                special_day_type = openapi_client.models._special_day_type_enum._SpecialDayTypeEnum(
                                    value = 'DAY_BEFORE_PUBLIC_HOLIDAY', 
                                    get_extended_value = '', ), 
                                public_event = openapi_client.models._public_event_type_enum._PublicEventTypeEnum(
                                    value = 'AGRICULTURAL_SHOW', 
                                    get_extended_value = '', ), 
                                named_areas = [
                                    openapi_client.models.named_area.NamedArea(
                                        area_name = openapi_client.models.multilingual_string.MultilingualString(
                                            values = openapi_client.models.values.Values(
                                                values = [
                                                    openapi_client.models.multilingual_string_value.MultilingualStringValue(
                                                        value = '', 
                                                        lang = '', )
                                                    ], ), ), 
                                        named_area_type = openapi_client.models.named_area_type_enum_g.NamedAreaTypeEnumG(
                                            value = 'applicationRegion', 
                                            extended_value_g = '', ), 
                                        country = '', 
                                        named_area_extension_g = openapi_client.models.named_area_extension_g.namedAreaExtensionG(), )
                                    ], 
                                get_special_day_extension = , )
                            ], 
                        get_period_extension = , ), 
                    get_measurement_or_calculation_time_extension = , 
                    time_precision = 'TENTHS_OF_SECOND', ),
        )
        """

    def testSiteMeasurements(self):
        """Test SiteMeasurements"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
